name: CI - TechFlow Task Manager

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build e Testes Automatizados
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compilar o projeto
        run: mvn compile --no-transfer-progress
        working-directory: projeto

      - name: Executar testes
        run: mvn test --no-transfer-progress
        working-directory: projeto
